//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloDemoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valo
    {
        public int ValoID { get; set; }
        public bool ValonTila { get; set; }
        public string ValonMaara { get; set; }
        public string Huone { get; set; }
    }
}
